### ISSUE TITLE
deletions/uncovered regions are not present/reported

### ISSUE THREAD

**Issue by tolot27** [cbg-ethz/ConsensusFixer#6]
I have a low coverage sequence set and mapped it to a reference. Some genomic regions have a coverage of 0 and I would expect `N`s in the consensus sequence, but they are not present, even if I adapt `-pluralityN`.

**Comment by tolot27** [comment]
The alignment statistics file (`statistics.txt` produced with the undocumented parameter `--stats`) lists all positions in the reference, which are covered. The not listed/uncovered positions should produce `N`s in the consensus sequence.

**Comment by armintoepfer** [comment]
Feel free to issue a PR. Nobody is working actively on the code base.

**Comment by armintoepfer** [comment]
If there is no coverage, nothing should be reported. Feel free to add a mode that adds `N`s for missing bases.
